### ISSUE TITLE
Rejecting promise in handle creates unhandled error

### ISSUE THREAD

**Issue by tshelburne** [burstable/node-beanstalkd-worker#3]
The following code results in `(node:18780) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): undefined` when `validate(data)` throws an error. It's running in Node v8.1.4.

```js
worker.handle(`validation`, data => {
	return new Promise(res => {
		res(validate(data))
	})
})
```

Because the worker is expecting either a resolved or rejected Promise, my assumption would be that rejected promises are handled by the library and registered as failures. If that's not the case, where should these rejections be managed?

**Comment by mickhansen** [comment]
new Promise should catch throws, this library certainly supports promises.
Are you sure validate throws synchronously?

**Comment by tshelburne** [comment]
Ah, yes, that was the problem. Thanks for the quick response.
